### ISSUE TITLE
Does it work now?

### ISSUE THREAD

**Issue by qwe321qwe321qwe321** [MizoTake/unity-license-activate#1]
I just tried and get errors at the beginning:
``` js
await page.goto('https://license.unity3d.com/manual')

await page.waitForNavigation({ // <--- it goes timeout.
  waitUntil: 'domcontentloaded'
})
```

**Comment by MizoTake** [comment]
Thank you for teaching me.

It seems to work in my macOS environment
Are you running in an environment other than macos?

**Comment by qwe321qwe321qwe321** [comment]
I run on Windows7 and Ubuntu18.04 and both fail.

**Comment by MizoTake** [comment]
It worked on linux before but it doesn't seem to work now, so I'll check it when I have time.

It seems that verification is not possible because you do not have Win7. I'm sorry.

**Comment by MizoTake** [comment]
@qwe321qwe321qwe321 I tried to modify the master branch, but it seems to be okay?

**Comment by qwe321qwe321qwe321** [comment]
It still doesn't work on Ubuntu18.04.

Log:
```
(node:10458) UnhandledPromiseRejectionWarning: TimeoutError: waiting for selector "input[id="type_personal"][value="personal"]" failed: timeout 30000ms exceeded
    at new WaitTask (/home/u/Desktop/unity-license-activate/node_modules/puppeteer/lib/DOMWorld.js:549:28)
    at DOMWorld._waitForSelectorOrXPath (/home/u/Desktop/unity-license-activate/node_modules/puppeteer/lib/DOMWorld.js:478:22)
    at DOMWorld.waitForSelector (/home/u/Desktop/unity-license-activate/node_modules/puppeteer/lib/DOMWorld.js:432:17)
    at Frame.waitForSelector (/home/u/Desktop/unity-license-activate/node_modules/puppeteer/lib/FrameManager.js:627:47)
    at Frame.<anonymous> (/home/u/Desktop/unity-license-activate/node_modules/puppeteer/lib/helper.js:112:23)
    at Page.waitForSelector (/home/u/Desktop/unity-license-activate/node_modules/puppeteer/lib/Page.js:1122:29)
    at /home/u/Desktop/unity-license-activate/activate.js:64:14
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:10458) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10458) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by MizoTake** [comment]
@qwe321qwe321qwe321 

I'm using Ubuntu with docker and thought maybe the command arguments are wrong or asking for two-factor authentication.

I've updated the README in hopes that it will help. Please confirm.

**Comment by MizoTake** [comment]
I'm sorry. The wait method didn't seem to be working well. I have included a correction.
